<?php
/**
 * @file
 * Code for the osha_authentication feature.
 */

include_once 'osha_authentication.features.inc';

/**
 * Implements hook_ldap_entry_pre_provision_alter().
 */
function osha_authentication_ldap_entry_pre_provision_alter(&$ldap_entries, $ldap_server, $context) {
  if ($context['action'] == 'update') {
    // Alter user password
    // @see http://www.openldap.org/faq/data/cache/347.html for {SHA} passwords
    foreach ($ldap_entries as $key => $entry) {
      if (isset($entry['userPassword'])) {
        $existing = is_array($entry['userPassword']) ? current($entry['userPassword']) : $entry['userPassword'];
        if (!empty($existing)) {
          $password = "{SHA}" . base64_encode(pack( "H*", sha1($existing)));
          $ldap_entries[$key]['userPassword'] = $password;
        }
      }
    }
  }
}


/**
 * Implements hook_user_login().
 *
 * A
 */
function osha_authentication_user_login(&$edit, $user) {
  if ($user->uid > 1) {
    $roles = osha_authentication_user_roles_sync($user, $user->ldap_proposed_roles);
    user_save($user, array('roles' => $roles));
    // LDAP_APPRV_US_01 - Assign Approver to the default list of approvers
    $is_approver = in_array('Approver', $user->roles);
    module_load_include('admin.inc', 'osha_authentication');
    osha_authentication_user_login_approver($user, $is_approver);
  }
}


/**
 * Implements hook_ldap_authorization_maps_alter().
 */
function osha_authentication_ldap_authorization_maps_alter($user, $ldap_user, $ldap_server, $consumer_conf, &$proposed_ldap_authorizations, $op) {
  module_load_include('admin.inc', 'osha_authentication');
  $user->ldap_proposed_roles = osha_map_ldap_role_to_drupal_role($proposed_ldap_authorizations);
}
