<?php

function osha_get_translatable_strings() {
  return array(
    'Section',
    'Article',
    'Activity',
    'Additional Resources',
    'Alt Text',
    'Archived',
    'Article type',
    'Body',
    'Character count',
    'Description',
    'Expiration Date',
    'Image',
    'Language',
    'Nace',
    'OSHwiki Category',
    'OSHwiki featured articles',
    'Page count',
    'Publication date',
    'Summary',
    'Tags',
    'Thesaurus',
    'Title',
    'Title Text',

    // Content from osha_blocks
    'Job Vacancies Reserve List',
    '<p class="Textfo" style="text-align: justify;">Reserve lists are composed of the candidates who came for an interview at the time of the recruitment procedure for the posts listed and who obtained the best overall marks.</p><p class="Textfo" style="text-align: justify;">Candidates in the reserve list may be offered contracts at a later date without subsequent selection procedure.</p><p class="Textfo" style="text-align: justify;">For some Contract Agent positions, EU-OSHA may use the EPSO database.</p>',
    '<div><ul><li>Latest <strong>news</strong> from <br>around the world</li><li>Forthcoming <br><strong>events</strong></li><li>Latest Agency <br><strong>publications</strong></li><li>Updates on EU <br><strong>legislation</strong></li><li>In 24 <br><strong>languages</strong></li><li><strong>Free</strong><br> subscriptions</li></ul></div>',
    '<p>Our publications range from in-depth research reports to topical e-facts, designed for use in the workplace. All are free to download. You can search the library by publication type or keyword. You might also like to subscribe to our free monthly newsletter — it makes keeping up to date with OSH easy.</p>',
    '<div><a class="seminar_back-to-seminars back-to-link" href="/tools-and-publications/seminars">Back to seminars</a></div>',
    '<p><a href="/jobs_archive">Closed vacancies</a></p>',
    '<div class="link"><span>Interested in specific topics?</span><a href="!url">Try Alert Service</a></div>',
    'OSHwiki Featured Articles',
    'OSHA archived content',
    '<div class="OSHWiki"><div class="separatorOsHWiki">&nbsp;</div><div id="OSHWikiDivTit"><div class="imgOSHWiki"><img src="/sites/all/themes/osha_frontend/images/OSHwiki.png" alt="" width="26" height="26"></div><div class="OSHWikiTitle">OSHwiki</div></div><div class="p2">Find OSHwiki articles<span><br></span></div><div class="p3"><a href="http://oshwiki.eu/wiki/Main_Page" target="_blank">Go to OSHwiki <img src="/sites/all/themes/osha_frontend/images/flecha.png" alt="Go to OSHwiki" width="19" height="11"></a></div></div>',

    // Core strings
    'Unable to send e-mail. Contact the site administrator if the problem persists.',
  );
}
