<?php

function osha_get_translatable_strings() {
  return array(
    'Related',
    'Section',
    'Article',
    'Activity',
    'Additional resources',
    'Archived',
    'Article type',
    'Body',
    'Character count',
    'Description',
    'Expiration date',
    'Image',
    'Language',
    'Nace',
    'OSHwiki category',
    'OSHwiki featured articles',
    'Page count',
    'Publication date',
    'Summary',
    'Tags',
    'Title',
    'Title text',

    // Strings form header
    'News & Events',
    'Press',
    'Contact us',
    'European Agency for Safety and Health at Work',

    // String from footer
    'an agency of the European Union',
    'Legal notice',
    'Site map',

    // Content from osha_blocks
    '<div class="link"><span>Interested in specific topics?</span><a href="!url">Try alert service</a></div>',
    'OSHwiki featured articles',
    'We are no longer actively maintaining this information, so don\'t be surprised if you find some broken links or if some of the information is out of date.',

    // Core strings
    'Unable to send e-mail. Contact the site administrator if the problem persists.',
    'Sorry, unrecognized username or password. Have you forgotten your password?',
    'Cancel user account',
    'User account',
    'Create new account',
    'Log in',
    'Request new password',
    'The e-mail address %mail is not valid.',
    'Enter your @s username.',
    'Enter the password that accompanies your username.',
    'Username or e-mail address',
    'Password reset instructions will be mailed to %email. You must log out to use the password reset link in the e-mail.',
    'Sorry, %name is not recognized as a user name or an e-mail address.',
    'Spaces are allowed; punctuation is not allowed except for periods, hyphens, apostrophes, and underscores.',
    'E-mail address',
    'A valid e-mail address. All e-mails from the system will be sent to this address. The e-mail address is not made public and will only be used if you wish to receive a new password or wish to receive certain news or notifications by e-mail.',
    'Go to page @number',
    'Go to first page',
    'Go to previous page',
    'Go to next page',
    'Go to last page',

    // Other strings
    'Share this article',
    'Share',
    'Recent tweets',
    'Clear filter',
    '- Any -',
    'More',
    'Press contacts',
    'EU-OSHA in the media',
    // Chosen.
    'Choose an option',
    'Choose some options',
    'No results match',
  );
}
