<?php
/**
 * @file
 * Code for the osha_wiki feature.
 */

include_once 'osha_wiki.features.inc';

define('OSHA_WIKI_CONTENT_TYPE', 'wiki_page');

/**
 * Define custom view mode for entities - wiki
 */
function osha_wiki_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['osha_wiki'] = array(
    'label' => t('OSH Wiki'),
    'custom settings' => TRUE,
  );
}

/* *
 * Implements hook_block_list_alter() to hide the related wiki under publication
 * when manual wiki articles have been linked to the current publication
 */

function osha_wiki_block_list_alter(&$blocks) {
    $node = menu_get_object();
    if ($node && !empty($node->field_related_oshwiki_articles[LANGUAGE_NONE][0])) {
        foreach ($blocks as $block_id => $block) {
            if ($block->delta == 'related_content-block_5') {
                unset ($blocks[$block_id]);
                break;
            }
        }
    }
}

/**
 * Implements hook_block_info().
 */
function osha_wiki_block_info() {
  $blocks = array();
  $blocks['osha_wiki_related_content'] = array(
    'info' => t('OSHwiki articles (with theme)'),
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'weight' => -3,
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  // Test URL: /node/875
  $blocks['osha_wiki_notopic'] = array(
    'info' => t('OSHwiki articles (no theme)'),
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'weight' => -3,
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * {@inheritdoc}
 */
function osha_wiki_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'osha_wiki_related_content':
      $block['subject'] = '';
      $block['content'] = osha_wiki_block_content();
      break;
    case 'osha_wiki_notopic':
      $block['subject'] = '';
      $block['content'] = osha_wiki_notopic_content();
      break;
  }
  return $block;
}

/**
 * Generates content for the related wiki articles block.
 *
 * @return string
 *   Block content
 */
function osha_wiki_block_content() {
  $node = menu_get_object();
  if (empty($node->field_wiki_categories[LANGUAGE_NONE][0]['tid'])) {
    // if wiki_category is not set, hide this block
    return NULL;
  }
  $category_id = $node->field_wiki_categories[LANGUAGE_NONE][0]['tid'];
  $category = taxonomy_term_load($category_id);
  $category_en_name = $category->name_original;
  $wiki_page_url = 'http://oshwiki.eu/wiki/Category:' . str_replace(' ', '_', $category_en_name);
  $find_more = t('Find OSHwiki articles on this theme');
  return osha_wiki_block_content_template($wiki_page_url, $find_more);
}

/**
 * Generates content for the related wiki articles block without a specific wiki category.
 *
 * @return string
 *   Block content
 */
function osha_wiki_notopic_content() {
  $wiki_page_url = 'http://oshwiki.eu/wiki/Main_Page';
  $find_more = t('Find OSHwiki articles');
  return osha_wiki_block_content_template($wiki_page_url, $find_more);
}

function osha_wiki_block_content_template($wiki_page_url, $find_more) {
  $wiki_name = t('OSHwiki');
  $goto_wiki = t('Go to OSHwiki');
  $content = '<div class="OSHWiki"><div class="separatorOsHWiki">&nbsp;</div><div id="OSHWikiDivTit"><div class="imgOSHWiki"><img src="/sites/all/themes/osha_frontend/images/OSHwiki.png" alt="" width="26" height="26" /></div><div class="OSHWikiTitle">'
    .$wiki_name
    .'</div></div><div class="p2">'
    .$find_more
    .'<span><br /></span></div><div class="p3"><a href="'
    .$wiki_page_url
    .'" target="_blank">'
    .$goto_wiki
    .' <img src="/sites/all/themes/osha_frontend/images/flecha.png" alt="'
    .$goto_wiki
    .'" width="19" height="11" /></a></div></div>';
  return $content;
}

/**
 * Implements hook_post_features_enable_feature().
 *
 * {@inheritdoc}
 */
function osha_wiki_post_features_enable_feature($component) {
  // After the field_instance ...
  if ($component == 'variable') {
    menu_rebuild();
    drupal_static_reset();
    if ($role = user_role_load_by_name('administrator')) {
      $permissions = array(
        'create wiki_page content',
        'edit own wiki_page content',
        'edit any wiki_page content',
        'delete own wiki_page content',
        'delete any wiki_page content',
      );
      user_role_grant_permissions($role->rid, $permissions);
    }
  }
}

/**
 * Validate that wiki_category is set when manual articles are added
 * see CW-534
 */
function osha_wiki_node_validate($node, $form, &$form_state) {
  if ($node->type == OSHA_ARTICLE_CONTENT_TYPE_ARTICLE && isset($node->field_related_oshwiki_articles)) {
    if (empty($node->field_wiki_categories[LANGUAGE_NONE][0]['tid']) && (
         !empty($node->field_related_oshwiki_articles[LANGUAGE_NONE][0]['target_id']) ||
         !empty($node->field_related_oshwiki_articles[LANGUAGE_NONE][1]['target_id']) 
        )) {
        form_set_error('field_wiki_categories', t('OSHwiki category is mandatory'));
    }
  }
}

/**
 * Implements hook_osha_tmgmt_i18n_string_list().
 */
function osha_wiki_osha_tmgmt_i18n_string_list() {
  module_load_include('inc', 'osha_wiki', 'osha_wiki.translations');
  return osha_wiki_get_translatable_strings();
}

/**
 * Implements hook_cron().
 */
function osha_wiki_cron() {
  watchdog('osha_wiki', "Running Wiki synchronisation cron job", array(), WATCHDOG_INFO);
  $migration = new OshaMigrateWiki(array());
  $migration->processImport();
}