<?php

function osha_wiki_get_translatable_strings() {
  return array(
    'OSHwiki featured articles',
    'Wiki Page',
    'Wiki articles',
    'Find OSHwiki articles on this theme',
    'OSHwiki Featured Articles',
    '<div class="OSHWiki"><div class="separatorOsHWiki">&nbsp;</div><div id="OSHWikiDivTit"><div class="imgOSHWiki"><img src="/sites/all/themes/osha_frontend/images/OSHwiki.png" alt="" width="26" height="26" /></div><div class="OSHWikiTitle">OSHwiki</div></div><div class="p2">!find_more<span><br /></span></div><div class="p3"><a href="!wiki_page_url" target="_blank">Go to OSHwiki <img src="/sites/all/themes/osha_frontend/images/flecha.png" alt="Go to OSHwiki" width="19" height="11" /></a></div></div>',
  );
}
