<?php

function osha_newsletter_get_translatable_strings() {
  return array(
    'Subscribe to OSHA Newsletter',
    'Display the latest newsletters',
    'Once our monthly update on safety and health at work. <a href="@newsletter_page_url">See more info</a><br/><p style="color : #dc2f82;">Join 65.000 subscribers!</p>',
    'Once a month, OSHmail keeps you updated on ocupational safety and health.<br/> You can sign up below:',
    'How will EU-OSHA use my details?',
    'OSHMail Newsletter',
    'Our latest newsletters',
    'Not interested anymore?',
    'Unsubscribe',
    'Privacy policy',
    'Subscribe',
    'The e-mail address is not valid.',
    'Please enter the e-mail address.',
    'No newsletters available.',
    'More news',
    'View the blog',
    'More events',
    'Occupational Safety and Health News &ndash; Europe',
    'Like what you&apos;re reading? <br/><a href="@url" style="@style">Tell a colleague</a>',
    'No longer wish to receive OSHmail? <a href="@url" style="@style">Unsubscribe here.</a>',
    'Subscribe to our <a href="@url" style="@style">Alert service</a> for <br/> customised content delivery',
    'Brought to you by EU-OSHA. Visit us at: <a href="@base_url" style="@style">@base_url</a>',
    'There was a problem sending your message and it was not sent.',
    'Your message has been sent to @emails.',
    'Please enter the e-mail address.',
    'The e-mail address is not valid.'
  );
}
