<?php

function osha_newsletter_get_translatable_strings() {
  return array(
    'Subscribe to EU-OSHA Newsletter',
    'Display the latest newsletters',
    'Once our monthly update on safety and health at work. <a href="@newsletter_page_url">See more info</a><br/>',
    'Once a month, OSHmail keeps you updated on ocupational safety and health.<br/> You can sign up below:',
    'How will EU-OSHA use my details?',
    'OSHMail newsletter',
    'Our latest newsletters',
    'Not interested anymore?',
    'Unsubscribe',
    'Privacy policy',
    'Privacy notice',
    'Subscribe',
    'The e-mail address is not valid.',
    'No newsletters available.',
    'More news',
    'View the blog',
    'More events',
    'Occupational Safety and Health News &ndash; Europe',
    'No longer wish to receive OSHmail? <a href="@url" style="@style">Unsubscribe here.</a>',
    'Subscribe to our <a href="@url" style="@style">Alert service</a> for <br/> customised content delivery',
    'Brought to you by EU-OSHA. Visit us at: <a href="@base_url" style="@style">@base_url</a>',
    'Your subscription has not been submitted because of a technical error.',
    'Your subscription has been submitted succesfully.',
    'Join',
    'subscribers'
  );
}
