<?php

/**
 * @file
 * Implements corporate CAPTCHA for use with the CAPTCHA module
 */

/**
 * Implements hook_menu().
 */
function corporate_captcha_menu() {
  $items = array();
  $items['admin/config/people/captcha/corporate_captcha'] = array(
    'title' => 'Corporate CAPTCHA',
    'file' => 'corporate_captcha.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('corporate_captcha_settings_form'),
    'access arguments' => array('administer CAPTCHA settings'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_captcha().
 */
function corporate_captcha_captcha($op, $captcha_type = '') {
  switch ($op) {
    case 'list':
      return array('CorporateCAPTCHA');

    case 'generate':
      if ($captcha_type == 'CorporateCAPTCHA') {

        $corporate_captcha_type = variable_get('corporate_captcha_type', 'string');

        $result = array();

        $captcha_path = drupal_get_path('module', 'corporate_captcha');
        drupal_add_js($captcha_path . '/captcha.js');
        require_once $captcha_path . '/captchalib.php';

        global $language;

        $create_captcha =
          '<SPAN class="captcha"><!--
          {
              "lang":"' . $language->language . '",
              "type":"' . $corporate_captcha_type . '",
              "length":"' . variable_get('corporate_captcha_length', 6) . '",
              "noise_level":"' . variable_get('corporate_captcha_noise_level', 0) . '",
              "case_sensitive":"' . variable_get('corporate_captcha_case_sensitive', 'false') . '",
              "autodetect_protocol":"' . variable_get('corporate_captcha_autodetect_protocol', 'true') . '",
              "perturbation":"' . variable_get('corporate_captcha_perturbation', 0.6) . '",
              "num_lines":"' . variable_get('corporate_captcha_num_lines', 8) . '",
              "noise_level":"' . variable_get('corporate_captcha_noise_level', 0) . '"
          }
          //--></SPAN>';

        $result['form']['captcha_image'] = array(
          '#type' => 'markup',
          '#markup' => $create_captcha,
          '#weight' => -1,
        );
        if ($corporate_captcha_type == 'string') {
          $title = t('What code is in the image?');
          $description = t('Enter the characters shown in the image.');
        }
        else {
          $title = t('Answer the math problem:');
          $description = t('Solve the problem and write the answer.');
        }
        $result['form']['captcha_response'] = array(
          '#type' => 'textfield',
          '#title' => $title,
          '#description' => $description,
          '#weight' => 0,
          '#name' => 'security_code',
          '#size' => 15,
          '#attributes' => array(
            'id' => 'security_code',
          ),
        );
        $result['captcha_validate'] = 'corporate_captcha_validation';
        $result['solution'] = '';

        return $result;
      }
      break;

  }
}

/**
 * Implements hook_validate().
 */
function corporate_captcha_validation() {
  $captcha_path = drupal_get_path('module', 'corporate_captcha');
  require_once $captcha_path . '/captchalib.php';
  $check = captcha_check_answer();
  return $check->is_valid;
}