<?php

function osha_legislation_get_translatable_strings() {
  return array(
    'Available in languages',
    'Expiration date',
    'Publication date',
    'Directive',
    'Legislation directives',
    'Guideline',
    'Legislation guidelines',
    'Free text search',
    'Legislation',
    'more',
    'Apply',
    'Reset',
    'Sort by',
    'Asc',
    'Desc',
    'No results',
    'Search',
    'Search directives',
    'Directive number',
    'Show details',
    'Guidelines by topics',
    'Date of directive',
  );
}
