<?php
/**
 * @file
 * Code for the HWC Partner feature.
 */

include_once 'hwc_partner.features.inc';
include_once 'hwc_partner.inc';

define ('PARTNER_TYPE_OCP', '825c3b00-0dd2-4026-b292-bc76d6e49a70');
define ('PARTNER_TYPE_MP', '8b662e6e-054a-4148-8495-490ac5858964');
define ('PARTNER_TYPE_FOP', '1dca3546-7c11-49b5-b74f-a77f87f60d96');



function hwc_partner_context_plugins() {
  $plugins = array();
  $plugins['hwc_context_condition_partner_page'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'hwc_partner') .'/context',
      'file' => 'hwc_context_condition_partner_page.inc',
      'class' => 'hwc_context_condition_partner_page',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
}

function hwc_partner_context_registry() {
  return array(
    'conditions' => array(
      'hwc_context_condition_partner_page' => array(
        'title' => t('Page belongs to partner'),
        'description' => t('Triggers context to check if page section is the same with current user section'),
        'plugin' => 'hwc_context_condition_partner_page',
      ),
    ),
  );
}

function hwc_partner_context_page_condition() {
  if ($plugin = context_get_plugin('condition', 'hwc_context_condition_partner_page')) {
    $plugin->execute();
  }
}

function hwc_partner_menu() {
  $items = array();
  $items['hwc_partner/autocomplete'] = array(
    'title' => '',
    'page callback' => 'hwc_partner_autocomplete_users_partners',
    'access callback' => 'masquerade_menu_access',
    'access arguments' => array('autocomplete'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function hwc_partner_block_info() {
  $blocks = array();
  $blocks_infos = array('Create an event', 'Create News', 'Private Area');
  foreach ($blocks_infos as $i => $title) {
    $blocks['hwc_partner_private_link_' . $i] = array(
      'info' => t('Private link block - ' . $title),
      'status' => 1,
      'region' => '-1',
      'visibility' => BLOCK_VISIBILITY_NOTLISTED,
      'cache' => DRUPAL_CACHE_GLOBAL,
    );
  }
  $blocks['hwc_partner_profile_title'] = array(
    'info' => t('My public profile'),
    'status' => 1,
    'region' => '-1',
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['hwc_partner_back_to_profile'] = array(
    'info' => t('Back to profile link'),
    'status' => 1,
    'region' => 'header',
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'cache' => DRUPAL_CACHE_PER_USER,
    'weight' => 50,
  );
  $blocks['hwc_partner_user_account_edit'] = array(
    'info' => t('User account edit link'),
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'cache' => DRUPAL_CACHE_PER_USER,
    'weight' => 60,
  );
  $blocks['hwc_partner_mostra_masquerade'] = array(
    'info' => t('Act as a partner'),
    'status' => 1,
    'region' => 'header',
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'cache' => DRUPAL_NO_CACHE,
    'weight' => 50,
  );
  return $blocks;
}

/**
 * Implements hook_field_extra_fields().
 */
function hwc_partner_field_extra_fields() {
  $extra['node']['partner']['display'] = array(
    'profile_update_link' => array(
      'label' => 'Profile update link',
      'description' => 'A link to update partner profile',
      'weight' => 0,
    ),
  );
  return $extra;
}

/**
 * Implements hook_block_configure().
 */
function hwc_partner_block_configure($delta = '') {
  $form = array();
  if (preg_match('/hwc_partner_private_link_[0-2]/', $delta)) {
    // Get the number of the block (0,1,2)
    $it = substr($delta, -1);
    $form['hwc_partner_private_link_' . $it . '_title'] = array(
      '#type' => 'textfield',
      '#title' => t('Link title'),
      '#size' => 60,
      '#description' => 'This text will appear at the top of the block.',
      '#default_value' => variable_get('hwc_partner_private_link_' . $it . '_title', ''),
    );
    $form['hwc_partner_private_link_' . $it . '_description'] = array(
      '#type' => 'textarea',
      '#title' => t('Description'),
      '#size' => 60,
      '#description' => 'This text will appear as a description under the title.',
      '#default_value' => variable_get('hwc_partner_private_link_' . $it . '_description', ''),
    );
    $form['hwc_partner_private_link_' . $it . '_link_text'] = array(
      '#type' => 'textfield',
      '#title' => t('Link text'),
      '#size' => 60,
      '#description' => 'This will appear after description. (e.g. "Click here").',
      '#default_value' => variable_get('hwc_partner_private_link_' . $it . '_link_text', ''),
    );
    $form['hwc_partner_private_link_' . $it . '_url'] = array(
      '#type' => 'textfield',
      '#title' => t('Link URL'),
      '#size' => 60,
      '#description' => 'This will be the url of the private link.',
      '#default_value' => variable_get('hwc_partner_private_link_' . $it . '_url', ''),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function hwc_partner_block_save($delta = '', $edit = array()) {
  // Get the number of the block (0,1,2)
  $it = substr($delta, -1);
  variable_set('hwc_partner_private_link_' . $it . '_title', $edit['hwc_partner_private_link_' . $it . '_title']);
  variable_set('hwc_partner_private_link_' . $it . '_description', $edit['hwc_partner_private_link_' . $it . '_description']);
  variable_set('hwc_partner_private_link_' . $it . '_link_text', $edit['hwc_partner_private_link_' . $it . '_link_text']);
  variable_set('hwc_partner_private_link_' . $it . '_url', $edit['hwc_partner_private_link_' . $it . '_url']);
}

/**
 * Implements hook_block_view().
 */
function hwc_partner_block_view($delta = '') {
  $block = array();
  global $user;
  if (preg_match('/hwc_partner_private_link_[0-2]/', $delta)) {
    $it = substr($delta, -1);
    $url = variable_get('hwc_partner_private_link_' . $it . '_url', '');
    $block['subject'] = '<none>';
    if ($node = menu_get_object()) {
      $visible =
        count(array_intersect(array(
          'administrator',
          ROLE_SUPERVISOR
        ), $user->roles))
        || (in_array(ROLE_CAMPAIGN_PARTNER, $user->roles) && hwc_partner_match_user_partner($node))
        || $user->uid == 1;
      // Media partners cannot create events, hide the block
      if ($delta == 'hwc_partner_private_link_0' && in_array(ROLE_CAMPAIGN_PARTNER, $user->roles) && hwc_partner_is_mp($node)) {
        $visible = FALSE;
      }
      if ($visible) {
        $url_options = array();
        if (count(array_intersect(array(
          'administrator',
          ROLE_SUPERVISOR
        ), $user->roles))) {
          reset($node->workbench_access);
          $id_section = current($node->workbench_access);
          $url_options = array('query' => array('workbench_access' => $id_section));
        }
        $block['content'] = theme('hwc_partner_private_link_' . $it, array(
            'hwc_partner_private_link_title' => l(t(variable_get('hwc_partner_private_link_' . $it . '_title')), $url, $url_options),
            'hwc_partner_private_link_description' => t(variable_get('hwc_partner_private_link_' . $it . '_description')),
            'hwc_partner_private_link_link_text' => l(t(variable_get('hwc_partner_private_link_' . $it . '_link_text')), $url),
            'node' => $node,
            'delta' => $delta,
          )
        );
      }
    }
  }
  else if ($delta == 'hwc_partner_profile_title') {
    // Did this to use it in panels.
    $block['title'] = '<none>';
    $block['content'] = '<h1>' . t('My public profile') . '</h1>';
  }
  else if ($delta == 'hwc_partner_user_account_edit') {
    // Did this to use it in panels.
    $block['title'] = '<none>';
    $block['content'] = l(t('Change password'), 'user/' . $user->uid . '/edit');
  }
  else if ($delta == 'hwc_partner_back_to_profile') {
    $link = NULL;
    // Sometimes the $user->workbench_access is empty, force a load of WBA data.
    if (empty($user->workbench_access)) {
      workbench_access_user_load_data($user);
    }
    if (in_array(ROLE_CAMPAIGN_PARTNER, $user->roles) && !empty($user->workbench_access)) {
      $sections = array_keys($user->workbench_access);
      foreach($sections as $id_section) {
        if ($partner = hwc_partner_by_section_id_load($id_section)) {
          // Did this to use it in panels.
          $block['title'] = '<none>';
          $block['content'] = l(t('Back to Private Zone'), 'node/' . $partner->nid);
          break;
        }
      }
    }
  }
  else if ($delta == 'hwc_partner_mostra_masquerade') {
    $block['title'] = '<none>';
    if (isset($_SESSION['masquerading'])) {
      $block['content'] = l(t('Switch back to your user'), 'masquerade/unswitch', array('query' => array('token' => drupal_get_token('masquerade/unswitch'))));
    }
    else if (user_access('masquerade as any user')) {
      $form = drupal_get_form('masquerade_block_1');
      $block['content'] = theme('hwc_partner_act_as_partner_block', array('content' => drupal_render($form)));
    }
  }
  return $block;
}

/**
 * Implements hook_views_pre_render().
 */
function hwc_partner_views_pre_render(&$view) {
  // Alter the more link.
  if ($view->name == 'partner_content') {
    if ($view->current_display == 'latest_partner_news') {
      $view->display_handler->set_option('link_display', 'custom_url');
      $view->display_handler->set_option('link_url', 'news');
    }
    else if ($view->current_display == 'latest_partner_events') {
      $view->display_handler->set_option('link_display', 'custom_url');
      $view->display_handler->set_option('link_url', 'events');
    }
  }
}

/**
 * Implements hook_theme().
 */
function hwc_partner_theme() {
  $theme = array();
  $path = drupal_get_path('module', 'hwc_partner');
  for ($it = 0; $it < 3; $it++) {
    $theme['hwc_partner_private_link_' . $it] = array(
      'template' => 'hwc_partner_private_link',
      'variables' => array(
        'hwc_partner_private_link_title' => NULL,
        'hwc_partner_private_link_description' => NULL,
        'hwc_partner_private_link_url' => NULL,
        'node' => NULL,
        'delta' => NULL,
      ),
      'path' => $path . '/templates',
    );
  }
  $theme['hwc_partner_act_as_partner_block'] = array(
    'template' => 'templates/hwc_partner_act_as_partner_block',
    'variables' => array(
      'content' => '',
    ),
  );
  return $theme;
}

function hwc_partner_form_masquerade_block_1_alter(&$form, &$form_state) {
  // Add our own autocomplete to show only partners users.
  if (!empty($form['masquerade_user_field']['#autocomplete_path'])) {
    $form['masquerade_user_field']['#autocomplete_path'] = 'hwc_partner/autocomplete';
    $form['#validate'] = array_merge(array('hwc_partner_form_masquerade_validate'), $form['#validate']);
  }
  if (!empty($form['masquerade_desc'])) {
    $form['masquerade_desc']['#markup'] = t('Find the partner by typing its name');
    $form['masquerade_desc']['#weight'] = -10;
  }
  array_unshift($form['#submit'], 'hwc_partner_form_masquerade_redirect');
  $form['submit']['#value'] = t('Switch account');
  $form['hint'] = array(
    '#type' => 'item',
    '#markup' => t('Hint: After switching to new partner account, there will be a link in the website header to switch back to your account'),
  );

  // @TODO: on key click must select the option from autocomplete, then submit the form.
  drupal_add_js("jQuery('#edit-masquerade-user-field').keydown(function(e) {if (e.keyCode == 13) { e.preventDefault(); }})",  array('type' => 'inline', 'scope' => 'footer'));
}

function hwc_partner_form_masquerade_validate($form, &$form_state) {
  $no_masq_roles = array_filter(variable_get('masquerade_admin_roles', array()));
  $name = $form_state['values']['masquerade_user_field'];
  $masq_user = user_load_by_name($name);
  if (empty($masq_user)) {
    form_set_error('masquerade_user_field', t('Could not switch to the selected account!'));
    return;
  }
  $inter_roles = array_intersect(array_keys($masq_user->roles), $no_masq_roles);
  if (!empty($inter_roles)) {
    form_set_error('masquerade_user_field', t('You can only switch to a partner'));
    return;
  }
}

function hwc_partner_form_masquerade_redirect($form, $form_state) {
  if (!empty($form_state['values']['masquerade_user_field']) && $account = user_load_by_name($form_state['values']['masquerade_user_field'])) {
    // If the user is a partner, redirect to the corresponding partner profile
    if (in_array(ROLE_CAMPAIGN_PARTNER, $account->roles) && !empty($account->workbench_access)) {
      $sections = array_keys($account->workbench_access);
      foreach ($sections as $id_section) {
        if ($partner = hwc_partner_by_section_id_load($id_section)) {
          $_SERVER['HTTP_REFERER'] = 'node/' . $partner->nid;
          break;
        }
      }
    }
  }
}

/**
 * Auto complete ajax user callback.
 */
function hwc_partner_autocomplete_users_partners($string) {
  $matches = array();
  if (strlen($string) > 1) {
    $partner_rid = 12;
    // Get users with only PARTNER role and with a section attached.
    $subquery = db_query('SELECT uid from users_roles GROUP BY uid HAVING COUNT(rid) = 1')->fetchCol();
    if (!empty($subquery)) {
      $query = db_select('users', 'u')->fields('u', array('uid', 'name'));
      $query->addField('t', 'name', 'partner_name');
      $query->innerJoin('users_roles', 'ur', 'u.uid = ur.uid');
      $query->innerJoin('workbench_access_user', 'wu', 'wu.uid = u.uid');
      $query->innerJoin('taxonomy_term_data', 't', 'wu.access_id = t.tid');
      $query->condition('ur.rid', $partner_rid);
      $or = db_or()
        ->condition('u.name', '%' . db_like(strtolower($string)) . '%', 'LIKE')
        ->condition('t.name', '%' . db_like(strtolower($string)) . '%', 'LIKE');
      $query->condition($or);
      $query->condition('u.uid', $subquery, 'IN');
      $result = $query->execute();
      while ($row = $result->fetchAssoc()) {
        $matches[$row['name']] = strtr('@user (@partner)', array('@user' => $row['name'], '@partner' => $row['partner_name']));
      }
    }
  }
  drupal_json_output($matches);
}

/**
 * Implements hook_node_access().
 */
function hwc_partner_node_access($node, $op, $account) {
  if ($op == 'view' && $node->nid == 253
    && (!in_array(ROLE_CAMPAIGN_PARTNER, $account->roles)
      && !in_array(ROLE_SUPERVISOR, $account->roles)
      && !in_array(ROLE_ADMINISTRATOR, $account->roles)
      && !in_array(ROLE_SUPERADMINISTRATOR, $account->roles))) {
    return NODE_ACCESS_DENY;
  }
  return NODE_ACCESS_IGNORE;
}

/**
 * Implements hook_node_view().
 */
function hwc_partner_node_view($node, $view_mode, $langcode) {
  global $user;
  if ($node->type == 'partner' && $view_mode == 'full') {
    $loginshell = NULL;
    $link_parameters = array('query' => array());
    if (in_array(ROLE_SUPERVISOR, $user->roles)
      || in_array(ROLE_ADMINISTRATOR, $user->roles)
      || in_array(ROLE_SUPERADMINISTRATOR, $user->roles)
    ) {
      // In case of these roles, partner's main contact GUID instead of user's guid
      $w = entity_metadata_wrapper('node', $node->nid);
      $loginshell = $w->field_guid_main_contact->value();
    }
    $user_is_partner = hwc_partner_match_user_partner($node);
    if ($user_is_partner) {
      $wu = entity_metadata_wrapper('user', $user->uid);
      $loginshell = $wu->field_crm_guid->value();
    }
    if (!empty($loginshell)) {
      $link_parameters['query']['session_id'] = $loginshell;
      $update_title = '<div class="hwc-partner-private-link-block-title">' . l(t('Update profile'), 'private/profile/update', $link_parameters) . '</div>';
      $update_content = '<div class="hwc-partner-private-link-block-description">'
        . t('Any modifications in your public profile? <a href="!link">Click here to update it.</a>', array('!link' => url('private/profile/update', $link_parameters)))
        . '</div>';
      $node->content['profile_update_link'] = array(
        '#type' => 'markup',
        '#markup' => $update_title . $update_content,
      );

    }
  }
  if (in_array(ROLE_CAMPAIGN_PARTNER, $user->roles) && $node->type == 'events' && $view_mode == 'full') {
    unset($node->content['field_schedule']);
  }

  // node 253 - /private/profile/update
  if ($node->nid == 253 && !empty($_GET['session_id']) && !empty($node->content['body'][0]['#markup'])) {
    $url = '/partner/forms/index.php?mf=TRUE&session_id=' . $_GET['session_id'];
    $c = 0;
    $node->content['body'][0]['#markup'] = str_replace('/partner/forms/index.php?mf=TRUE"', $url . '"', $node->content['body'][0]['#markup'], $c);
    if ($c != 1) {
      drupal_set_message('Warning! The page might not work properly due to failure to find the form URL. Please contact technical support');
    }
  }
  // node 225 - /partner/register
  if ($node->nid == 225 && !empty($_GET['session_id']) && !empty($node->content['body'][0]['#markup'])) {
    $url = '/partner/forms/index.php?session_id=' . $_GET['session_id'];
    $c = 0;
    $node->content['body'][0]['#markup'] = str_replace('/partner/forms/index.php"', $url . '"', $node->content['body'][0]['#markup'], $c);
    if ($c != 1) {
      drupal_set_message('Warning! The page might not work properly due to failure to find the form URL. Please contact technical support');
    }
  }
}


/**
 * Implements hook_pathologic_alter().
 *
 * Some links such as FOP, are starting with fop/ and do need to be "fixed"
 * due to HTTP server redirects.
 */
function hwc_partner_pathologic_alter(&$url_params, $parts, $settings) {
  if (preg_match('/^\/partner\/forms\//m', $url_params['path'])) {
    $url_params['options']['use_original'] = TRUE;
  }
}

/**
 * Implements hook_node_delete().
 */
function hwc_partner_node_delete($node) {
  if ($node->type == 'partner') {
    $w = entity_metadata_wrapper('node', $node->nid);
    if ($guid = $w->field_guid_organisation->value()) {
      if ($term = osha_workflow_get_partner_section_by_guid($guid)) {
        taxonomy_term_delete($term->tid);
      }
    }
  }
}

/**
 * Implements hook_path_breadcrumbs_view_alter().
 */
function hwc_partner_path_breadcrumbs_view_alter(&$breadcrumbs, $path_breadcrumbs, $contexts) {
  if (in_array($path_breadcrumbs->machine_name, array('partner_draft_news', 'partner_draft_events'))) {
    $node = node_load($contexts['node']->argument);
    switch ($node->field_partner_type[LANGUAGE_NONE][0]['tid']) {
      case 185:
        /* Official Campaign Partners */
        $url = l(t('Official Campaign Partners'), 'official-campaign-partners');
        break;

      case 186:
        /* Media Partners */
        $url = l(t('Media Partners'), 'campaign-media-partners');
        break;

      default:
        /* National Focal Points */
        $url = l(t('National Focal Points'), 'national-focal-points');
        break;
    }
    // Alter the URL to partners page considering the partner type.
    $breadcrumbs[2] = $url;
  }
}

/*
 * Implements hook_node_presave().
 *
 * HCW-1065 The author of the content should be the logged in user, not the
 * masqueraded one.
 */
function hwc_partner_node_presave($node) {
  if (isset($_SESSION['masquerading'])) {
    // If Supervisor (masqueraded) switch account to record the correct author
    global $user; /* Masqueraded user */
    $_SESSION['masqueraded_user'] = $user->uid;
    masquerade_switch_back();
    $user_original = user_load_by_name(get_current_user());
    if (!$node->nid) {
      $node->uid  = $user_original->uid;
      $node->name = $user_original->name;
      $node->log = 'Created by ' . $user_original->name . '.';
    }
    else {
      $node->log = 'Edited by ' . $user_original->name . '.';
    }
  }
}

/**
 * Implements hook_node_insert().
 */
function hwc_partner_node_insert($node) {
  _hwc_partner_masquerade_reswitch();
}

/**
 * Implements hook_node_update().
 */
function hwc_partner_node_update($node) {
  _hwc_partner_masquerade_reswitch();
}

function _hwc_partner_masquerade_reswitch() {
  if (isset($_SESSION['masqueraded_user'])) {
    masquerade_switch_user($_SESSION['masqueraded_user']);
    unset ($_SESSION['masqueraded_user']);
  }
}
