<?php

function osha_publication_get_translatable_strings() {
  return array(
    'Sort by',
    'Asc',
    'Desc',
    'Items per page',
    '- All -',
    'EU Bookshop: You can order a printed copy of this document',
    'Publications',
    'Publication',
    'Show details',
    'Back to publications and filter',
    'OSHwiki featured articles',
    'Additional resources',
    'Activity',
    'Archived',
    'Author(s)',
    'OSHwiki categories',
    'Publication date',
    'Related publications',
    'Unpublished',
    'Filter results',
  );
}
