<?php
/**
 * @file
 * Code for the Press Contact feature.
 */

include_once 'osha_press_contact.features.inc';

/**
 * Implements hook_osha_tmgmt_i18n_string_list().
 */
function osha_press_contact_osha_tmgmt_i18n_string_list() {
  module_load_include('inc', 'osha_press_contact', 'osha_press_contact.translations');
  return osha_press_contact_get_translatable_strings();
}

/**
 * Implements Elysia hook_cronapi().
 */
function osha_press_contact_cronapi() {
  return array('osha_press_contact_cron' => array(
    'description' => 'Synchronize focal points from CRM XML file (if changed)',
    'rule' => '0 0 1 * *', // Each 1st of month (12:00 AM)
  ));
}

/**
 * Implements hook_cron().
 */
function osha_press_contact_cron() {
  module_load_include('inc', 'migrate_ui', 'migrate_ui.pages');
  migrate_autoregister();
  // Update Focal Point Migration.
  $migrate = osha_migration_migrate_api();
  $migrations = array(OSHA_MIGRATION_CONTENT_TYPE_FOCAL_POINT, OSHA_MIGRATION_CONTENT_TYPE_BOARD_BUREAU);
  foreach ($migrations as $migration) {
    $file = $migrate['migrations'][$migration]['file_name'];
    $filemtime = filemtime($file);
    if ($filemtime === FALSE) {
      watchdog('osha_press_contact', 'File @file not found!', array('@file' => $file), WATCHDOG_WARNING);
      return;
    }
    else {
      $var_name = 'osha_press_contact_import_file_modify_time_' . $migration;
      $last_modification = variable_get($var_name, 0);
      if ($filemtime > $last_modification) {
        osha_press_contact_migrate($migration);
        variable_set($var_name, $filemtime);
      }
    }
  }
}

/**
 * Triggers Import of a migration by name.
 */
function osha_press_contact_migrate($machine_name) {
  $migration = Migration::getInstance($machine_name);
  $migration->prepareUpdate();
  $total = $migration->sourceCount();
  watchdog('osha_press_contact', 'Starting Rollback @migration',
    array('@migration' => $machine_name), WATCHDOG_INFO);
  $result = $migration->processRollback(array('limit' => $total, 'force' => FALSE));
  watchdog('osha_press_contact', 'Rolled back @migration with result: @result',
    array('@migration' => $machine_name, '@result' => $result), WATCHDOG_INFO);

  watchdog('osha_press_contact', 'Starting Import @migration',
    array('@migration' => $machine_name), WATCHDOG_INFO);
  $migration->processImport(array('limit' => $total, 'force' => FALSE));
  watchdog('osha_press_contact', 'Imported @migration with result: @result',
    array('@migration' => $machine_name, '@result' => $result), WATCHDOG_INFO);
}
