<?php
/**
 * @file
 * Code for the Press Contact feature.
 */

include_once 'osha_press_contact.features.inc';

/**
 * Implements hook_cron().
 */
function osha_press_contact_cron() {
  // Update Focal Point Migration.
  $migrate = osha_migration_migrate_api();
  $file = $migrate['migrations'][OSHA_MIGRATION_CONTENT_TYPE_FOCAL_POINT]['file_name'];
  $filemtime = filemtime($file);
  if ($filemtime === FALSE) {
    watchdog('FocalPointImport', 'File @file not found!', array('@file' => $file), WATCHDOG_WARNING);
    return;
  }
  else {
    $last_modification = variable_get('osha_focal_point_import_file_modify_time', 0);
    if ($filemtime > $last_modification) {
      drush_invoke('migrate-auto-register');
      drush_set_option('update', TRUE);
      drush_invoke('migrate-import', array('FocalPoint'));
      variable_set('osha_focal_point_import_file_modify_time', $filemtime);
    }
  }
}
