<?php

function osha_calls_get_translatable_strings() {
  return array(
    'Archived calls',
    'Calls quicktab',
    'Ongoing calls',
    'Open calls',
    'Currently, there are no calls available in this section.',
    'Processed calls for contractors',
    'Open calls for contractors',
    'Ongoing calls for contractors',
    '<a href="/inside-eu-osha/procurement">Back to calls</a>',
    'View all',
    '-- Please select type --',
    'Back to calls',
    'Calls',
  );
}
