<?php

function osha_search_get_translatable_strings() {
  return array(
    'Search',
    'No results',
    'Relevance',
    'Site search',
    'Publication date',
    'Language',
    'OSHwiki search',
    'Date',
    'Sort by',
    'Items per page',
    '- All -',
    'Content type',
    'Available in languages',
    'Item language',
    'Reset',
    'Asc',
    'Desc',
    'Order',
    '<span class="result_summary">Displaying @start - @end of @total</span>',
  );
}
