<?php
/**
 * @file
 * Code for the hwc_homepage feature.
 */

include_once 'hwc_homepage.features.inc';

/**
 * Implements hook_views_pre_render
 * {@inheritdoc}
 */
function hwc_homepage_views_pre_render(&$view){
  if ($view->name == 'frontpage_slider' && drupal_is_front_page()) {
    $jssor_path = libraries_get_path('jquery-slider-master');
    drupal_add_js($jssor_path . '/jssor.slider.mini.js');
    drupal_add_css($jssor_path . '/jssor.css');

    // Add "alt" attribute to images.
    foreach ($view->result as &$item) {
      if ($item->field_field_image[0]['rendered']['#item']['alt'] == NULL) {
        $item->field_field_image[0]['rendered']['#item']['alt'] = $item->field_field_image[0]['rendered']['#item']['filename'];
      }
    }
  }
}

/**
 * Implements hook_block_info().
 */
function hwc_homepage_block_info() {
  $blocks = array();
  $blocks['hwc_homepage_tools_and_resources'] = array(
    'info' => t('Tools and publications'),
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}


/**
 * Implements hook_block_configure().
 */
function hwc_homepage_block_configure($delta = '') {
  $form = array();
  if ($delta == 'hwc_homepage_tools_and_resources') {
    $form['hwc_homepage_tools_and_resources_message'] = array(
      '#type' => 'textarea',
      '#title' => t('Message'),
      '#description' => 'The message shown underneath',
      '#default_value' => variable_get('hwc_homepage_tools_and_resources_message'),
    );
  }
  return $form;
}

/**
 * Implements hook_form_alter().
 */
function hwc_homepage_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'block_admin_configure'
    && !empty($form['delta']['#value'])
    && $form['delta']['#value'] == 'menu-information-tailored') {
    $form['intro_text'] = array(
      '#type' => 'textarea',
      '#title' => 'Introductive text',
      '#default_value' => variable_get('menu_information_tailored_intro_text', 'We provide information specifically for the following groups, to enable everyone to get involved in the campaign in a way that makes sense for them'),
      '#weight' => -1,
    );
    $form['#submit'][] = 'hwc_homepage_info_tailored_intro_text';
  }
}

function hwc_homepage_info_tailored_intro_text($form, &$form_state) {
  $intro_text = $form_state['values']['intro_text'];
  variable_set('menu_information_tailored_intro_text', $intro_text);
}


/**
 * Implements hook_block_save().
 */
function hwc_homepage_block_save($delta = '', $edit = array()) {
  if ($delta == 'hwc_homepage_tools_and_resources') {
    variable_set('hwc_homepage_tools_and_resources_message', $edit['hwc_homepage_tools_and_resources_message']);
  }
}


/**
 * Implements hook_block_view().
 */
function hwc_homepage_block_view($delta = '') {
  $block = array();
  if ($delta == 'hwc_homepage_tools_and_resources') {
    $block['content']['message'] = array(
      'type' => 'item',
      '#prefix' => '<div class="text-muted">',
      '#markup' => t(variable_get('hwc_homepage_tools_and_resources_message')),
      '#suffix' => '</div>',
    );
    $links = menu_tree('main-menu');
    $block['content']['menu'] = $links[1372]['#below'];
  }
  return $block;
}

function hwc_homepage_panels_pane_content_alter($content, $pane, $args, $contexts) {
  if (!empty($pane->subtype) && $pane->subtype == 'menu-menu-information-tailored') {
    $intro_text = t(variable_get('menu_information_tailored_intro_text', 'We provide information specifically for the following groups, to enable everyone to get involved in the campaign in a way that makes sense for them'));
    $content->content['#prefix'] = '<p>' . $intro_text . '</p>';
  }
}

/**
 * Implements hook_block_view_alter().
 */
function hwc_homepage_block_view_alter(&$data, $block) {
  if ($block->delta == 'partners-block_1') {
    $data['content']['#markup'] .= '<div class="more-link">' . l(t('See all partners'), 'official-campaign-partners') . '</div>';
  }
}