<?php
/**
 * @file
 * Code for the Infographics feature.
 */

include_once 'osha_infographics.features.inc';

define('OSHA_INFOGRAPHIC_CONTENT_TYPE_INFOGRAPHIC', 'infographic');

/**
 * Implements hook_views_pre_render().
 * @param $view
 */
function osha_infographics_views_pre_render(&$view){
  if ($view->name == 'infographic' && $view->current_display == 'block_2') {
    $view->attachment_before = l(t('All topics'), current_path());
  }
}

/**
 * Implements hook_osha_tmgmt_i18n_string_list().
 */
function osha_infographics_osha_tmgmt_i18n_string_list() {
  module_load_include('inc', 'osha_infographics', 'osha_infographics.translations');
  return osha_infographics_get_translatable_strings();
}

/**
 * Implements hook_field_formatter_info().
 */
function osha_infographics_field_formatter_info() {
  $info = array(
    'multilanguage_file' => array(
      'label' => t('Multilanguage File'),
      'field types' => array('file'),
      'description' => t('Download file in: EN, BG ...'),
    ),
    'multilanguage_image' => array(
      'label' => t('Multilanguage Image'),
      'field types' => array('image'),
      'description' => t('Download image in EN, BG ...'),
    ),
  );
  return $info;
}

/**
 * Implements hook_field_formatter_view().
 */
function osha_infographics_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'multilanguage_file':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#theme' => 'osha_infographics_multilanguage_file_format',
          '#entity' => $entity,
          '#file' => $item,
          '#delta' => $delta,
        );
      }
      break;
    case 'multilanguage_image':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#theme' => 'osha_infographics_multilanguage_image_format',
          '#entity' => $entity,
          '#file' => $item,
          '#delta' => $delta,
        );
      }
      break;
  }
  return $element;
}

/**
 * Implements hook_theme().
 */
function osha_infographics_theme() {
  return array(
    'osha_infographics_multilanguage_file_format' => array(
      'variables' => array('entity' => NULL, 'file' => NULL, 'delta' => NULL),
    ),
    'osha_infographics_multilanguage_image_format' => array(
      'variables' => array('entity' => NULL, 'file' => NULL, 'delta' => NULL),
    ),
  );
}

/*
* Formats multilanguage file for download
*/
function theme_osha_infographics_multilanguage_file_format($element) {
  $file = (object) $element['file'];
  $entity = (object) $element['entity'];
  $icon_directory = drupal_get_path('theme', 'osha_frontend') . '/images/file_icons';

  global $language;
  $file = isset($entity->field_file[$language->language][0])
    ? $entity->field_file[$language->language][0]
    : $entity->field_file['en'][0];
  $output = "<span class='label_multilang_file'>Download</span>";
  $output .= theme_file_icon(
    array(
      "file" => file_load($file['fid']),
      "icon_directory" => $icon_directory
  ));
  $output .="<span class='label_multilang_file'>in:</span>";

  foreach($entity->field_file as $lang => $object) {
    $output .=  '<a href="' . file_create_url($object[0]['uri']) . '" target="_blank">' . strtoupper($lang) . '</a> | ';
  }
  $output = substr($output, 0, -3);
  return $output;
}

/*
* Formats multilanguage image
*/
function theme_osha_infographics_multilanguage_image_format($element) {
  $file = (object) $element['file'];
  $entity = (object) $element['entity'];
  $icon_directory = drupal_get_path('theme', 'osha_frontend') . '/images/file_icons';

  global $language;
  $file = isset($entity->field_image[$language->language][0])
    ? $entity->field_image[$language->language][0]
    : $entity->field_image['en'][0];
  $output = "<span class='label_multilang_file'>Open</span>";
  $output .= theme_file_icon(
    array(
      "file" => file_load($file['fid']),
      "icon_directory" => $icon_directory
    ));
  $output .="<span class='label_multilang_file'>in:</span>";

  foreach($entity->field_image as $lang => $object) {
    $output .=  '<a href="' . file_create_url($object[0]['uri']) . '" target="_blank">' . strtoupper($lang) . '</a> | ';
  }
  $output = substr($output, 0, -3);
  return $output;
}
