<?php
/**
 * @file
 * Code for the Infographics feature.
 */

include_once 'osha_infographics.features.inc';

define('OSHA_INFOGRAPHIC_CONTENT_TYPE_INFOGRAPHIC', 'infographic');

function osha_infographics_workbench_access_node_element_alter(&$element, $form_state, $active) {
  if (isset($form_state['build_info']['form_id']) && $form_state['build_info']['form_id'] == 'infographic_node_form' ) {
    // CW-800 default value for Section
    $element['#required'] = FALSE;
    foreach ($element['#options'] as $key=>$option) {
      if (preg_match('/^[-\\s]*Infographic/', $option)) {
        $element['#default_value'] = $key;
        break;
      }
    }
  }
}

/**
 * Implements hook_views_pre_render().
 * @param $view
 */
function osha_infographics_views_pre_render(&$view){
  if ($view->name == 'infographic' && $view->current_display == 'block_2') {
    $view->attachment_before = "<a href='/tools-and-publications/infographics'>All topics</a>";
  }
}
