<?php
/**
 * @file
 * Code for the HWC gallery feature.
 */

include_once 'hwc_gallery.features.inc';

/**
 * Implements hook_node_view().
 */
function hwc_gallery_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'hwc_gallery' && $view_mode == 'full') {
    $wrapper = entity_metadata_wrapper('node', $node);
    $first_image = $wrapper->field_images->value()[0];
    if (!empty($first_image)) {
      $url = image_style_url('article_image', $first_image['uri']);
      $node->content['cover_image'] = array(
        '#markup' => '<img class="img-responsive" src="' . $url . '"/>',
        '#weight' => 0,
      );
    }
  }
}

/**
 * Implementation of hook_galleryformatter_styles().
 * @see galleryformatter_gallery_galleryformatter_styles
 */
function hwc_gallery_galleryformatter_styles() {
  $gallerystyles_directory = drupal_get_path('theme', 'hwc_frontend') . '/gallerystyles';
  $files = file_scan_directory($gallerystyles_directory, '/\.css$/');
  $gallerystyles = array();
  foreach ($files as $file) {
    // Skip RTL files.
    if (!strpos($file->name, '-rtl')) {
      $gallerystyles[$file->uri] = drupal_ucfirst($file->name);
    }
  }
  return $gallerystyles;
}
