<?php
/**
 * @file
 * Code for the Resources feature.
 */

include_once 'osha_resources.features.inc';

/**
 * Define custom view mode for entities - wiki
 */
function osha_resources_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['osha_resources'] = array(
    'label' => t('Additional resource'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_node_view
 * @param $node
 * @param $view_mode
 * @param $langcode
 */
function osha_resources_node_view_alter(&$build){
  if($build['#bundle'] == 'youtube'){
    if(isset($build['field_youtube']) && $build['field_youtube']['#formatter'] == 'youtube_thumbnail'){
      foreach($build['field_youtube'] as $key => $youtube){
        if(is_array($youtube) && isset($youtube['#image_link']['options']))
          $build['field_youtube'][$key]['#image_link']['options']['attributes']['target'] = '_blank';
      }
    }
  }
}

/**
 * Implements hook_osha_tmgmt_i18n_string_list().
 */
function osha_resources_osha_tmgmt_i18n_string_list() {
  module_load_include('inc', 'osha_resources', 'osha_resources.translations');
  return osha_resources_get_translatable_strings();
}
