<?php

include_once 'hwc.features.inc';



function hwc_req_param($form_state, $name, $default = NULL) {
  if (!empty($form_state['values'][$name])) {
    $ret = $form_state['values'][$name];
    if (is_array($ret)) {
      $ret = array_filter($ret);
    }
    return $ret;
  }
  if (!empty($_GET[$name])) {
    if (is_array($_GET[$name])) {
      $ret = array();
      foreach($_GET[$name] as $v) {
        $ret[] = check_plain($v);
      }
      return $ret;
    }
    else {
      return check_plain($_GET[$name]);
    }
  }
  return $default;
}