<?php
/**
 * @file
 * hwc.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function hwc_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
  if ($module == "linkit" && $api == "linkit_profiles") {
    return array("version" => "1");
  }
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_image_default_styles().
 */
function hwc_image_default_styles() {
  $styles = array();

  // Exported image style: medium_large.
  $styles['medium_large'] = array(
    'label' => 'Medium large (330x330)',
    'effects' => array(
      2 => array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 330,
          'height' => 330,
          'upscale' => 0,
        ),
        'weight' => 2,
      ),
    ),
  );

  // Exported image style: medium_thumbnail_mc.
  $styles['medium_thumbnail_mc'] = array(
    'label' => 'Medium thumbnail manual crop (350 X 350)',
    'effects' => array(
      5 => array(
        'name' => 'manualcrop_crop_and_scale',
        'data' => array(
          'width' => 350,
          'height' => 350,
          'upscale' => 0,
          'respectminimum' => 1,
          'onlyscaleifcrop' => 0,
          'style_name' => 'medium_thumbnail_mc',
        ),
        'weight' => 0,
      ),
    ),
  );

  // Exported image style: small_thumbnail_mc_150_150.
  $styles['small_thumbnail_mc_150_150'] = array(
    'label' => 'Small Thumbnail Manual Crop (150X150)',
    'effects' => array(
      3 => array(
        'name' => 'manualcrop_crop_and_scale',
        'data' => array(
          'width' => 150,
          'height' => 150,
          'upscale' => 0,
          'respectminimum' => 1,
          'onlyscaleifcrop' => 0,
          'style_name' => 'small_thumbnail_mc_150_150',
        ),
        'weight' => 0,
      ),
    ),
  );

  return $styles;
}
