<?php


/**
 * Implements Elysia hook_cronapi().
 */
function ncw_migration_cronapi() {
  return array(
    'ncw_migration_run' => array(
      'description' => 'Synchronize with corporate website',
      'arguments' => array('events'),
      'rule' => '0 22 * * *', // Every day at 22:00
    )
  );
}


function ncw_migration_run() {
  /* BE AWARE OF THE MIGRATIONS ORDERING! */
  $migrations = array(
    'tax_country_status',
    'tax_country',
    'tax_fop_link_sections',
    'tax_newsletter_sections',
    'tax_publication_types',
    'tax_tags',

    'events',
    'infographic',
    'news',
    'note_to_editor',
    'press_contact',
    'press_release',
    'publications',
  );
  foreach($migrations as $migration) {
    ncw_migration_run_single($migration);
  }
}

/**
 * @param string $machine_name
 *   Migration machine name
 *
 * @return boolean
 *   Returns TRUE if migration was successful
 *
 * @throws \Exception
 */
function ncw_migration_run_single($machine_name) {
  migrate_static_registration(array($machine_name));
  /** @var Migration $migration */
  $migration = Migration::getInstance($machine_name);
  $migration->prepareUpdate();
  $result = $migration->processImport();
  if ($result != MigrationBase::RESULT_COMPLETED) {
    watchdog(
      'ncw_migration',
      '[CRON]Last CW import did not finished successfully (machine:!machine_name)',
      array('!machine_name' => $machine_name)
    );
    return FALSE;
  }
  return TRUE;
}
