<?php

function osha_contact_get_translatable_strings() {
  return array(
    'Contact us',
    'Type of sender',
    'Please select one',
    'Country',
    'Thank you for your feedback. We appreciate your comments about the
  European Agency for Safety and Health at Work and we try, wherever possible, to answer your emails.
  Unfortunately, due to the large volume of correspondence we receive, we are unable to offer a personal reply
  in each case. However, we read all your comments, and we use your feedback to improve our websites and services.
  <br /><br />
  You can stay up to date with new developments to our website by visiting our
  “<a href="@link1">What’s new</a>” pages
  and subscribing to our electronic newsletter
  <a href="@link2">OSHmail</a>.',
    'Topic',
    'Your name',
    'Your e-mail address',
    'Send message',
    'Message',
    'Please Enter a valid email address.',
  );
}
