<?php
/**
 * @file
 * Code for the OSHA Events feature.
 */

include_once 'osha_events.features.inc';

/**
 * Implements hook_form_alter().
 */

function osha_events_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'events_node_form') {

    $form['#validate'][] = 'osha_events_form_validate';

    // Activity field changes
    if (isset($form['field_activity'][LANGUAGE_NONE][0])) {
      unset($form['field_activity'][LANGUAGE_NONE]['add_more']);
      // Extract the field field tree to change cardinality
      $field = $form['field_activity'][LANGUAGE_NONE][0]['tid'];

      // Show the label as usual
      unset($field['#title_display']);

      // Field is not required, so add also an empty option.
      $field['#required'] = FALSE;
      $field['#options'] = array('' => t('- None -')) + $field['#options'];
      // Switch validator
      $field['#element_validate'] = array('options_field_widget_validate');

      $form['field_activity'][LANGUAGE_NONE] = $field;
    }
  }
}

/**
 * Implements hook_form_views_exposed_form_alter().
 */
function osha_events_form_views_exposed_form_alter(&$form, &$form_state) {
  // CW-1085 Default date now for start date in views filter.
  if ($form['#id'] == 'views-exposed-form-events-index-page') {
    $form['field_start_date_value']['#date_format'] = 'd/m/Y';
    $form['field_start_date_value2']['#date_format'] = 'd/m/Y';
    if (empty($form_state['input'])) {
      $date = new DateTime('now');
      $form_state['input']['field_start_date_value']['date'] = $date->format('d/m/Y');
      // Set the get value to prevent a bug in pager
      // See ticket CW-1438 and Drupal bug: www.drupal.org/node/1415306
      $_GET['field_start_date_value']['date'] = $date->format('d/m/Y');
    }
  }
}

/**
 * Validation callback.
 */
function osha_events_form_validate($form, &$form_state) {
  // When publishing an event, some fields are required.
  $values = $form_state['values'];
  $node = $form_state['node'];
  if ($values['status'] == 1) {
    if (FALSE && empty($values['body'][$node->language]['0']['value'])) {
      form_set_error('body', t('You have to add a Description.'));
    }
    if (empty($values['field_start_date']['und']['0']['value'])) {
      form_set_error('field_start_date', t('You have to add a Start Date.'));
    }
    if (empty($values['field_start_date']['und']['0']['value2'])) {
      form_set_error('field_start_date', t('You have to add an End Date .'));
    }
    if (FALSE && empty($values['field_website_of_event']['und']['0']['title'])) {
      form_set_error('field_website_of_event', t('You have to add a Web site title.'));
    }
    if (FALSE && empty($values['field_website_of_event']['und']['0']['url'])) {
      form_set_error('field_website_of_event', t('You have to add a Web site url.'));
    }
    if (empty($values['field_country_code']['und']['0']['value'])) {
      form_set_error('field_country_code', t('You have to add a Country Code.'));
    }
    if (empty($values['field_city']['und']['0']['value'])) {
      form_set_error('field_city', t('You have to add a City.'));
    }
    if (empty($values['field_tags']['und']['0']['tid'])) {
      form_set_error('field_tags', t('You have to add a Category.'));
    }
  }
}


/**
 * Altering Date Popup to remove labels and description for specific field
 */
function osha_events_date_popup_process_alter(&$element, &$form_state, $context) {
  if ($element['#name'] == 'field_start_date_value' || $element['#name'] == 'field_start_date_value2') {
    //unset($element['date']['#description']);
    unset($element['date']['#title']);
  }
}

/**
 * Implements hook_osha_tmgmt_i18n_string_list().
 */
function osha_events_osha_tmgmt_i18n_string_list() {
  module_load_include('inc', 'osha_events', 'osha_events.translations');
  return osha_events_get_translatable_strings();
}


/**
 * Implements hook_user_role_insert().
 */
function osha_events_user_role_insert($role) {
  if ($role->name == 'Events Editor') {
    user_role_grant_permissions($role->rid, array(
      'access contextual links',
      'access dashboard',

      'create files',
      'view own private files',
      'view own files',
      'view files',

      'edit own image files',
      'edit any image files',
      'delete own image files',
      'download own image files',
      'download any image files',

      'use text format full_html',
      'use text format filtered_html',

      'access media browser',

      'edit meta tags',
      'access content',
      'view own unpublished content',
      'view revisions',

      'create events content',
      'edit own events content',
      'edit any events content',
      'delete own events content',
      'delete any events content',

      'create url aliases',
      'access administration pages',
      'view the administration theme',
    ));
  }
}

/**
 * Implements hook_views_pre_render().
 *
 * {@inheritdoc}
 */
function osha_events_views_pre_render(&$view) {
  if ($view->name == 'events' && in_array($view->current_display, array('block_1', 'block_2'))) {
    $month = '';
    $current_year = date('Y', time());

    foreach ($view->result as $key => $result) {
      $row_month = format_date(strtotime($result->field_field_start_date[0]['raw']['value']), 'custom', 'M');
      $row_month_raw = date('m', strtotime($result->field_field_start_date[0]['raw']['value']));
      $row_year = date('Y', strtotime($result->field_field_start_date_1[0]['raw']['value']));

      // Remove from display if start date is in the same month.
      if ($month == $row_month) {
        unset($view->result[$key]);
        continue;
      }
      $month = $row_month;

      $path = $view->current_display == 'block_1'? 'past-events':'events';

      $result->field_field_start_date[0]['rendered']['#markup']
        = l($row_month, $path, array(
          'query' =>
            array('f' => array(
                0 => urlencode('field_start_date:') . 'value:' . $row_year . '-' . $row_month_raw,
              )
            )
          )
        );
    }
  }

  // Breadcrumb and title for Monthly Posts.
  if ($view->name == 'events_search' && $view->current_display == 'page_2') {
    $title = isset($view->args[0]) ? osha_events_get_view_title($view->args[0]) : '';
    // Set view title.
    $view->build_info['title'] = $title;
    // Set view breadcrumb.
    drupal_set_breadcrumb(
      array(
        l(t('Media centre'), '<front>'),
        l(t('Events'), 'events'),
        $title,
      )
    );
  }
}

/**
 * Display custom title for monthly views.
 *
 * @return bool|null|string
 *   View's title.
 */
function osha_events_get_view_title($title) {
  if (preg_match('/([\d]{4}\-[\d]{2})/', $title)) {
    $title = date(
      'F Y',
      mktime(0, 0, 0, substr($title, 5, 2), 1, substr($title, 0, 4))
    );
    $title = t('@data events', array('@data' => $title));
  }
  return $title;
}

